- name: Pull docker image of Calculator
  hosts: host_machine
  tasks:        
    - name: pull docker image
      shell: docker pull docker.io/divyanshi2241/mini_project:latest
      
    - name: running container
      shell: docker run -i -d divyanshi2241/mini_project:latest